version: "3.1"

services:
  nut:
    image: "teknologist/webnut"
    container_name: "webnut"
    environment:
      - UPS_HOST=192.168.137.109
      - UPS_PORT=3493
      - UPS_USER=admin
      - UPS_PASSWARD=sec
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 6543:6543
